name = "serramatutu's theme"
license = 'MIT'
description = 'My blog theme'

tags = ['blog']

enableEmoji = true

[author]
  name = 'serramatutu'
  homepage = 'serramatutu.io'

[markup]
  [markup.highlight]
    noClasses = false
