baseURL = "https://serramatutu.io/"
languageCode = "en-us"
theme = "serramatutu"
enableEmoji = true

title = "serramatutu"

[params]
smallSummaryThreshold = 500

# Allow raw HTML
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1

